### ISSUE TITLE
Deploy job fails if two commits are pushed in short succession

### ISSUE THREAD

**Issue by Pandapip1** [spdx/license-list-XML#2477]
See https://github.com/spdx/license-list-XML/actions/runs/9094142729

This can be easily solved by adding the following to the workflow:

```yml
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```
